--- #YAML:1.0
name:               IPTables-Rule
version:            0.01
abstract:           Perl extension for holding iptables rule information in objects.
author:
    - Phillip Smith <fukawi2@(none)>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
